### ISSUE TITLE
How to update forked repo?

### ISSUE THREAD

**Issue by imarkonis** [KVHEM/drought_uncertainty#6]
Before making any changes locally, or pulling from our personal repo the forked version of the project we should synchronize it with the main repo. But how?

**Comment by hanel** [comment]
First, you have to add remote pointing to the original repo (often called "upstream")

To list your remotes try (e.g. in the RStudio terminal [not R console])

`git remote -v`

To add new remote called "upstream" pointing to our repo

`git remote add upstream https://github.com/KVHEM/drought_uncertainty.git`

Then download code from upstream

`git fetch upstream`

and merge with your local master branch

`git merge upstream/master`

Depending on changes you made it may be necessary to resolve conflicts or even delete some files.
